services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: first_ai_website_try-web:latest
    container_name: subm-web
    ports:
      - "127.0.0.1:33001:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: first_ai_website_try-backend:latest
    container_name: subm-backend
    env_file:
      - /opt/1panel/apps/First_AI_Website_Try/.env
    volumes:
      - /opt/1panel/apps/First_AI_Website_Try/Jan:/app/server/data
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
